name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@master
    - name: Deploy beta to Lambda
      uses: mariamrf/py-lambda-action@v1.0.0
      with:
        lambda_layer_arn: 'arn:aws:lambda:us-west-2:307851781232:layer:stock-api-requirements'
        lambda_function_name: 'stocks-api'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'
